# Generated by Django 4.2.2 on 2023-07-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="Arbeits_liste",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="Rest_liste",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Familie", "Familie"),
                    ("Firma", "Firma"),
                    ("Herr", "Herr"),
                    ("Herr Dr.", "Herr Dr."),
                    ("Herr Prof.", "Herr Prof."),
                    ("Frau", "Frau"),
                    ("Frau Dr.", "Frau Dr."),
                ],
                max_length=20,
            ),
        ),
    ]
