# Generated by Django 4.2.2 on 2023-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0002_vertriebangebot_arbeits_liste_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="modul_anzahl_ticket",
            field=models.IntegerField(default=0),
        ),
    ]
