# Generated by Django 4.2.2 on 2023-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0003_alter_vertriebangebot_modul_anzahl_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="Full_ticket_preis",
            field=models.FloatField(default=0.0),
        ),
    ]
