# Generated by Django 4.2.2 on 2023-07-12 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0005_alter_vertriebangebot_modulanzahl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="batteriemodule_ticket",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="eddi_ticket",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="modulanzahl",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="notstrom_ticket",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="optimizer_ticket",
            field=models.IntegerField(default=0),
        ),
    ]
