# Generated by Django 4.2.2 on 2023-07-12 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vertrieb_interface",
            "0006_alter_vertriebangebot_batteriemodule_ticket_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="arbeitspreis",
            field=models.FloatField(
                default=46.8, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="prognose",
            field=models.FloatField(
                default=5.2, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="verbrauch",
            field=models.FloatField(
                default=15000, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="zeitraum",
            field=models.PositiveIntegerField(default=15),
        ),
    ]
