# Generated by Django 4.2.2 on 2023-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0008_vertriebangebot_status_change_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="status_change_field",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
