# Generated by Django 4.2.2 on 2023-07-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0009_alter_vertriebangebot_status_change_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="countdown_on",
            field=models.BooleanField(default=False),
        ),
    ]
