# Generated by Django 4.2.2 on 2023-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0010_vertriebangebot_countdown_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="module_ticket",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Phono Solar PS420M7GFH-18/VNH", "Phono Solar PS420M7GFH-18/VNH"),
                    (
                        "Jinko Solar Tiger Neo N-type JKM425N-54HL4-B",
                        "Jinko Solar Tiger Neo N-type JKM425N-54HL4-B",
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="solar_module",
            field=models.CharField(
                choices=[
                    ("Phono Solar PS420M7GFH-18/VNH", "Phono Solar PS420M7GFH-18/VNH"),
                    (
                        "Jinko Solar Tiger Neo N-type JKM425N-54HL4-B",
                        "Jinko Solar Tiger Neo N-type JKM425N-54HL4-B",
                    ),
                ],
                default="Phono Solar PS420M7GFH-18/VNH",
                max_length=100,
            ),
        ),
    ]
