# Generated by Django 4.2.2 on 2023-07-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0011_alter_vertriebangebot_module_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="module_ticket",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="solar_module",
            field=models.CharField(
                default="Phono Solar PS420M7GFH-18/VNH", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="wallboxtyp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
