# Generated by Django 4.2.2 on 2023-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("vertrieb_interface", "0012_alter_vertriebangebot_module_ticket_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomLogEntry",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="anz_wandhalterung_fuer_speicher",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="wandhalterung_fuer_speicher",
            field=models.BooleanField(default=False),
        ),
    ]
