# Generated by Django 4.2.2 on 2023-08-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0013_customlogentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="total_anzahl",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
