# Generated by Django 4.2.2 on 2023-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0014_vertriebangebot_total_anzahl"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="vorname_nachname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
