# Generated by Django 4.2.2 on 2023-08-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0016_alter_vertriebangebot_garantiewr"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="elwa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="elwa_typ",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="thor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="thor_typ",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
