# Generated by Django 4.2.2 on 2023-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vertrieb_interface",
            "0017_vertriebangebot_elwa_vertriebangebot_elwa_typ_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("angenommen", "angenommen"),
                    ("bekommen", "bekommen"),
                    ("in Kontakt", "in Kontakt"),
                    ("Kontaktversuch", "Kontaktversuch"),
                    ("abgelehnt", "abgelehnt"),
                    ("abgelaufen", "abgelaufen"),
                    ("on Hold", "on Hold"),
                    ("storniert", "storniert"),
                ],
                default="in Kontakt",
                max_length=255,
                null=True,
            ),
        ),
    ]
