# Generated by Django 4.2.2 on 2023-08-21 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0018_alter_vertriebangebot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="kabelanschluss",
            field=models.FloatField(
                blank=True,
                default=10.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
