# Generated by Django 4.2.2 on 2023-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0019_alter_vertriebangebot_kabelanschluss"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="heizstab",
            field=models.BooleanField(default=False),
        ),
    ]
