# Generated by Django 4.2.2 on 2023-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0020_vertriebangebot_heizstab"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="elwa_ticket",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="heizstab_ticket",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="thor_ticket",
            field=models.IntegerField(default=0),
        ),
    ]
