# Generated by Django 4.2.2 on 2023-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0021_vertriebangebot_elwa_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="wandhalterung_fuer_speicher_ticket",
            field=models.IntegerField(default=0),
        ),
    ]
