# Generated by Django 4.2.2 on 2023-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vertrieb_interface",
            "0022_vertriebangebot_wandhalterung_fuer_speicher_ticket",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="zahlungsbedingungen",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
