# Generated by Django 4.2.5 on 2023-09-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0023_vertriebangebot_zahlungsbedingungen"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="ag_fetched_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
