# Generated by Django 4.2.5 on 2023-10-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0024_vertriebangebot_ag_fetched_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="hersteller",
            field=models.CharField(default="Huawei", max_length=100),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="speicher_model",
            field=models.CharField(default="LUNA 2000", max_length=100),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="wechselrichter_model",
            field=models.CharField(default="SUN 2000", max_length=100),
        ),
    ]
