# Generated by Django 4.2.5 on 2023-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0025_vertriebangebot_hersteller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="gesamtkapazitat",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
