# Generated by Django 4.2.5 on 2023-10-05 10:51

from django.db import migrations, models
import vertrieb_interface.models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0026_vertriebangebot_gesamtkapazitat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="anz_speicher",
            field=models.PositiveIntegerField(
                default=0, validators=[vertrieb_interface.models.validate_range]
            ),
        ),
    ]
