# Generated by Django 4.2.5 on 2023-10-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0027_alter_vertriebangebot_anz_speicher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="hersteller",
            field=models.CharField(default="----", max_length=100),
        ),
    ]
