# Generated by Django 4.2.5 on 2023-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0028_alter_vertriebangebot_hersteller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="speicher_model",
            field=models.CharField(default="----", max_length=100),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="wechselrichter_model",
            field=models.CharField(default="----", max_length=100),
        ),
    ]
