# Generated by Django 4.2.5 on 2023-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0029_alter_vertriebangebot_speicher_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="angebot_zoho_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
