# Generated by Django 4.2.5 on 2023-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0030_vertriebangebot_angebot_zoho_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="text_for_email",
            field=models.TextField(blank=True, null=True),
        ),
    ]
