# Generated by Django 4.2.5 on 2023-11-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0031_vertriebangebot_text_for_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="text_for_email",
            field=models.TextField(
                blank=True,
                default="\n                Sehr geehrter Interessent,\n\n                anbei wie besprochen das Angebot im Anhang als PDF-Dokument.\n\n                Bei Fragen stehen wir Ihnen gern jederzeit zur Verfügung!\n                \n\n                Wir wünschen Ihnen einen schönen Tag und würden uns über eine positive Rückmeldung freuen\n                ",
                null=True,
            ),
        ),
    ]
