# Generated by Django 4.2.5 on 2023-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0032_alter_vertriebangebot_text_for_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="name",
            field=models.CharField(blank=True, default="------", max_length=100),
        ),
    ]
