# Generated by Django 4.2.5 on 2023-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0033_alter_vertriebangebot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("angenommen", "angenommen"),
                    ("bekommen", "bekommen"),
                    ("in Kontakt", "in Kontakt"),
                    ("Kontaktversuch", "Kontaktversuch"),
                    ("abgelehnt", "abgelehnt"),
                    ("abgelaufen", "abgelaufen"),
                    ("on Hold", "on Hold"),
                    ("storniert", "storniert"),
                ],
                default="",
                max_length=255,
                null=True,
            ),
        ),
    ]
