# Generated by Django 4.2.5 on 2023-11-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0034_alter_vertriebangebot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_backup_box",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_solar_module",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_speichermodule",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_wallbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_wechselrichter",
            field=models.BooleanField(default=False),
        ),
    ]
