# Generated by Django 4.2.5 on 2023-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0035_vertriebangebot_datenblatter_backup_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="angebot_and_calc_pdf",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
