# Generated by Django 4.2.5 on 2024-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vertrieb_interface", "0036_vertriebangebot_angebot_and_calc_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_optimizer",
            field=models.BooleanField(default=False),
        ),
    ]
