# Generated by Django 5.0.2 on 2024-02-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0037_vertriebangebot_datenblatter_optimizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="status_pva",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
