# Generated by Django 5.0.2 on 2024-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0038_vertriebangebot_status_pva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="angebot_id_assigned",
            field=models.BooleanField(default=True),
        ),
    ]
