# Generated by Django 5.0.2 on 2024-03-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0039_alter_vertriebangebot_angebot_id_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="zoho_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="zoho_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
