# Generated by Django 5.0.2 on 2024-03-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0040_vertriebangebot_zoho_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="garantieWR",
            field=models.CharField(
                choices=[
                    ("keine", "keine"),
                    ("10 Jahre", "10 Jahre"),
                    ("15 Jahre", "15 Jahre"),
                    ("20 Jahre", "20 Jahre"),
                    ("25 Jahre", "25 Jahre"),
                ],
                default="10 Jahre",
                max_length=10,
            ),
        ),
    ]
