# Generated by Django 5.0.2 on 2024-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0041_alter_vertriebangebot_garantiewr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="anrede",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Familie", "Familie"),
                    ("Firma", "Firma"),
                    ("Herr", "Herr"),
                    ("Herr Dr.", "Herr Dr."),
                    ("Herr Prof.", "Herr Prof."),
                    ("Frau", "Frau"),
                    ("Frau Prof.", "Frau Prof."),
                    ("Frau Dr.", "Frau Dr."),
                ],
                max_length=20,
            ),
        ),
    ]
