# Generated by Django 5.0.2 on 2024-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0042_alter_vertriebangebot_anrede"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_thor",
            field=models.BooleanField(default=False),
        ),
    ]
