# Generated by Django 5.0.2 on 2024-03-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0043_vertriebangebot_datenblatter_thor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="angebot_id_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
