# Generated by Django 5.0.2 on 2024-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0044_alter_vertriebangebot_angebot_id_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="angebot_display_value",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
