# Generated by Django 5.0.2 on 2024-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0045_vertriebangebot_angebot_display_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="angenommenes_angebot",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
