# Generated by Django 5.0.2 on 2024-04-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0046_vertriebangebot_angenommenes_angebot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editierbarer_Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField(default="<<kein editierbarer text>>")),
                ("font", models.CharField(default="JUNO Solar Lt", max_length=100)),
                ("font_size", models.IntegerField(default=11)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dokument_PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Dokument PDF Vertrieb", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "editable_texts",
                    models.ManyToManyField(to="vertrieb_interface.editierbarer_text"),
                ),
            ],
        ),
    ]
