# Generated by Django 5.0.2 on 2024-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0048_editierbarer_text_x_editierbarer_text_y_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editierbarer_text",
            name="content",
            field=models.TextField(
                default="<<kein editierbarer text>>", help_text="Inhalt"
            ),
        ),
    ]
