# Generated by Django 5.0.2 on 2024-05-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0050_alter_editierbarer_text_x_alter_editierbarer_text_y",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="angebot_display_value",
        ),
    ]
