# Generated by Django 5.0.2 on 2024-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0051_remove_vertriebangebot_angebot_display_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="smartmeter_model",
            field=models.CharField(default="----", max_length=100),
        ),
    ]
