# Generated by Django 5.0.2 on 2024-05-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0052_vertriebangebot_smartmeter_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="datenblatter_smartmeter",
            field=models.BooleanField(default=False),
        ),
    ]
