# Generated by Django 5.0.2 on 2024-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0053_vertriebangebot_datenblatter_smartmeter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="hersteller",
            field=models.CharField(default="Huawei", max_length=100),
        ),
    ]
