# Generated by Django 5.0.2 on 2024-05-29 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0054_alter_vertriebangebot_hersteller"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="smartmeter_angebot_price",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
