# Generated by Django 5.0.2 on 2024-06-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0055_vertriebangebot_smartmeter_angebot_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="angebot_and_calc_pdf",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="angebot_pdf_admin",
        ),
    ]
