# Generated by Django 5.0.2 on 2024-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0056_remove_vertriebangebot_angebot_and_calc_pdf_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="garantieWR",
            field=models.CharField(
                choices=[
                    ("keine", "keine"),
                    ("10 Jahre", "10 Jahre"),
                    ("15 Jahre", "15 Jahre"),
                ],
                default="10 Jahre",
                max_length=10,
            ),
        ),
    ]
