# Generated by Django 5.0.2 on 2024-08-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0057_alter_vertriebangebot_garantiewr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="eddi",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="eddi_angebot_price",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="eddi_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="elwa_typ",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="thor_typ",
        ),
    ]
