# Generated by Django 5.0.2 on 2024-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0058_remove_vertriebangebot_eddi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="genehmigung_rabatt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="rabatt",
            field=models.IntegerField(default=0),
        ),
    ]
