# Generated by Django 5.0.2 on 2024-08-27 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0062_vertriebangebot_beta_platte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="rabatt",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
