# Generated by Django 5.0.2 on 2024-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0063_alter_vertriebangebot_rabatt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="garantieWR",
            field=models.CharField(
                choices=[
                    ("keine", "keine"),
                    ("10 Jahre", "10 Jahre"),
                    ("15 Jahre", "15 Jahre"),
                ],
                default="15 Jahre",
                max_length=10,
            ),
        ),
    ]
