# Generated by Django 5.0.2 on 2024-08-28 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0064_alter_vertriebangebot_garantiewr"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="anzahlung",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="effektiver_zins",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="gesamtkreditbetrag",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="laufzeit",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="monatliche_rate",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="nettokreditbetrag",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="sollzinssatz",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="vertriebangebot",
            name="garantieWR",
            field=models.CharField(
                choices=[
                    ("keine", "keine"),
                    ("10 Jahre", "10 Jahre"),
                    ("15 Jahre", "15 Jahre"),
                ],
                default="10 Jahre",
                max_length=10,
            ),
        ),
    ]
