# Generated by Django 5.0.2 on 2024-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0066_vertriebangebot_finanzierung"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="ausweisung_rabatt",
            field=models.BooleanField(default=False),
        ),
    ]
