# Generated by Django 5.0.2 on 2024-09-03 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0067_vertriebangebot_ausweisung_rabatt"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="rabattsumme",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
