# Generated by Django 5.0.2 on 2024-09-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0068_vertriebangebot_rabattsumme"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="prefa_befestigung",
            field=models.BooleanField(default=False),
        ),
    ]
