# Generated by Django 5.0.2 on 2024-11-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0069_vertriebangebot_prefa_befestigung"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vertriebangebot",
            old_name="potenzialausgleich",
            new_name="potentialausgleich",
        ),
    ]
