# Generated by Django 5.0.2 on 2024-11-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0070_rename_potenzialausgleich_vertriebangebot_potentialausgleich",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="datenblatter_thor",
        ),
    ]
