# Generated by Django 5.0.2 on 2024-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0071_remove_vertriebangebot_datenblatter_thor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="rabattaktion",
            field=models.CharField(default="----", max_length=100),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="rabattaktion_included",
            field=models.BooleanField(default=False),
        ),
    ]
