# Generated by Django 5.0.2 on 2024-11-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0072_vertriebangebot_rabattaktion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vertriebangebot",
            old_name="rabattaktion",
            new_name="sonderrabatt",
        ),
        migrations.RenameField(
            model_name="vertriebangebot",
            old_name="rabattaktion_included",
            new_name="sonderrabatt_included",
        ),
    ]
