# Generated by Django 5.0.2 on 2024-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0073_rename_rabattaktion_vertriebangebot_sonderrabatt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="geruestOeffentlich",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebangebot",
            name="smartDongleLte",
            field=models.BooleanField(default=False),
        ),
    ]
