# Generated by Django 5.0.2 on 2024-12-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0075_vertriebticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebticket",
            name="ablehnungs_grund",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="anfrage_ber",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="b2b_partner",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="empfohlen_von",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="leadstatus",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="termine_id",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="termine_text",
        ),
    ]
