# Generated by Django 5.0.2 on 2024-12-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0076_remove_vertriebticket_ablehnungs_grund_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebticket",
            name="ausrichtung",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="komplex",
        ),
    ]
