# Generated by Django 5.0.2 on 2025-01-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0077_remove_vertriebticket_ausrichtung_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="hub_included",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="hub_included",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="kabelanschluss",
        ),
    ]
