# Generated by Django 5.0.2 on 2025-01-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0078_remove_vertriebangebot_hub_included_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebticket",
            name="hersteller",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="wechselrichter_model",
        ),
    ]
