# Generated by Django 5.0.2 on 2025-01-30 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0079_remove_vertriebticket_hersteller_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebticket",
            name="modulanzahl",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(-50)]
            ),
        ),
    ]
