# Generated by Django 5.0.2 on 2025-01-30 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0080_alter_vertriebticket_modulanzahl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebticket",
            name="anzOptimizer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vertriebticket",
            name="modulanzahl",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(-50)]
            ),
        ),
    ]
