# Generated by Django 5.0.2 on 2025-01-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0081_alter_vertriebticket_anzoptimizer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="Full_ticket_preis",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="batteriemodule_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="elwa_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="fullticketpreis",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="heizstab_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="modul_anzahl_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="module_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="notstrom_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="optimizer_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="thor_ticket",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="ticket_pdf",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="total_anzahl",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="wandhalterung_fuer_speicher_ticket",
        ),
    ]
