# Generated by Django 5.0.2 on 2025-02-05 12:00

import vertrieb_interface.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0082_remove_vertriebangebot_full_ticket_preis_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebticket",
            name="anz_speicher",
            field=models.IntegerField(
                default=0, validators=[vertrieb_interface.utils.validate_range]
            ),
        ),
    ]
