# Generated by Django 5.0.2 on 2025-02-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0083_alter_vertriebticket_anz_speicher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebticket",
            name="gesamtkapazitat",
        ),
    ]
