# Generated by Django 5.0.2 on 2025-02-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0084_remove_vertriebticket_gesamtkapazitat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="gesamtkapazitat",
        ),
    ]
