# Generated by Django 5.0.2 on 2025-02-14 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0086_vertriebangebot_ersatzstrom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebangebot",
            name="kabelanschluss",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
