# Generated by Django 5.0.2 on 2025-02-20 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0087_alter_vertriebangebot_kabelanschluss"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebticket",
            name="kabelanschluss",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
