# Generated by Django 5.0.2 on 2025-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0088_vertriebticket_kabelanschluss"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="wp_kombi_rabatt",
            field=models.BooleanField(default=False),
        ),
    ]
