# Generated by Django 5.0.2 on 2025-03-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0089_vertriebangebot_wp_kombi_rabatt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="genehmigung_rabatt",
        ),
    ]
