# Generated by Django 5.0.2 on 2025-03-18 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0090_remove_vertriebangebot_genehmigung_rabatt"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebticket",
            name="ausweisung_rabatt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="indiv_price",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="indiv_price_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="rabatt",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="sonderrabatt",
            field=models.CharField(default="----", max_length=100),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="sonderrabatt_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="wp_kombi_rabatt",
            field=models.BooleanField(default=False),
        ),
    ]
