# Generated by Django 5.0.2 on 2025-04-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0092_vertriebticket_rabattsumme"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="indiv_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="indiv_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
