# Generated by Django 5.0.2 on 2025-06-13 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0094_alter_vertriebangebot_indiv_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="kabelSmartGuard",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="kabelSmartGuard",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
