# Generated by Django 5.0.2 on 2025-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0095_vertriebangebot_kabelsmartguard_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vertriebangebot",
            old_name="anlagenstandort",
            new_name="postanschrift",
        ),
        migrations.RenameField(
            model_name="vertriebticket",
            old_name="anlagenstandort",
            new_name="postanschrift",
        ),
    ]
