# Generated by Django 5.0.2 on 2025-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0096_rename_anlagenstandort_vertriebangebot_postanschrift_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="postanschrift_ort",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="postanschrift_ort",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
