# Generated by Django 5.0.2 on 2025-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0097_vertriebangebot_postanschrift_ort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="postanschrift_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="postanschrift_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
