# Generated by Django 5.0.2 on 2025-09-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0098_vertriebangebot_postanschrift_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="apzFeldUVV",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="apzFeldUVV",
            field=models.BooleanField(default=False),
        ),
    ]
