# Generated by Django 5.0.2 on 2025-09-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vertrieb_interface",
            "0099_vertriebangebot_apzfelduvv_vertriebticket_apzfelduvv",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebticket",
            name="wr_tausch",
            field=models.CharField(default="----", max_length=100),
        ),
    ]
