# Generated by Django 5.0.2 on 2025-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0100_vertriebticket_wr_tausch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertriebticket",
            name="wr_tausch",
            field=models.CharField(default="Kein Tausch", max_length=100),
        ),
    ]
