# Generated by Django 5.0.2 on 2025-10-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0101_alter_vertriebticket_wr_tausch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="ablehnungs_grund",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="leadstatus",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="notstrom",
        ),
        migrations.RemoveField(
            model_name="vertriebangebot",
            name="notstrom_angebot_price",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="notstrom",
        ),
        migrations.RemoveField(
            model_name="vertriebticket",
            name="notstrom_angebot_price",
        ),
    ]
