# Generated by Django 5.0.2 on 2026-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0102_remove_vertriebangebot_ablehnungs_grund_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vertriebangebot",
            name="zaehlerschrank_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vertriebticket",
            name="zaehlerschrank_2",
            field=models.BooleanField(default=False),
        ),
    ]
