# Generated by Django 5.0.2 on 2026-03-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vertrieb_interface", "0103_vertriebangebot_zaehlerschrank_2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vertriebangebot",
            old_name="optimizer_angebot_price",
            new_name="zubehoer_angebot_price",
        ),
        migrations.RenameField(
            model_name="vertriebticket",
            old_name="optimizer_angebot_price",
            new_name="zubehoer_angebot_price",
        ),
    ]
