# Generated by Django 4.2.2 on 2023-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0002_solarmodulepreise"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallboxpreise",
            name="in_stock",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
