# Generated by Django 4.2.2 on 2023-08-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_wallboxpreise_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarmodulepreise",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
