# Generated by Django 4.2.2 on 2023-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_solarmodulepreise_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anderekonfigurationwerte",
            name="value",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
