# Generated by Django 5.0.2 on 2024-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0006_solarmodulepreise_module_garantie"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarmodulepreise",
            name="leistungs_garantie",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
