# Generated by Django 5.0.2 on 2024-06-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0007_solarmodulepreise_leistungs_garantie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elektrikpreis",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="elektrikpreis",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="modulegarantiepreise",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="modulegarantiepreise",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="modulepreise",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="modulepreise",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="optionalaccessoriespreise",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="optionalaccessoriespreise",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="solarmodulepreise",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="solarmodulepreise",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="wallboxpreise",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="wallboxpreise",
            name="old_price",
        ),
    ]
