# Generated by Django 5.0.2 on 2024-06-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0010_alter_solarmodulepreise_zuschlag"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarmodulepreise",
            name="datenblatt",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
