# Generated by Django 5.0.2 on 2024-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0012_rename_modulegarantiepreise_wrgarantiepreise"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarmodulepreise",
            name="filename",
            field=models.CharField(default="Solarmodule", max_length=255),
        ),
        migrations.AddField(
            model_name="wallboxpreise",
            name="datenblatt",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="wallboxpreise",
            name="filename",
            field=models.CharField(default="Wallbox", max_length=255),
        ),
    ]
