# Generated by Django 5.0.2 on 2024-08-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0013_solarmodulepreise_filename_wallboxpreise_datenblatt_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModulePreise",
            new_name="KwpPreise",
        ),
    ]
