# Generated by Django 5.0.2 on 2024-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0015_wallboxpreise_pdf_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallboxpreise",
            name="pdf_text",
            field=models.TextField(
                default="<<kein editierbarer text>>", help_text="Inhalt"
            ),
        ),
    ]
