# Generated by Django 5.0.2 on 2024-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0016_alter_wallboxpreise_pdf_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionalaccessoriespreise",
            name="pdf_text",
            field=models.TextField(
                default="<<kein editierbarer text>>", help_text="Inhalt"
            ),
        ),
    ]
