# Generated by Django 5.0.2 on 2024-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0017_optionalaccessoriespreise_pdf_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionalaccessoriespreise",
            name="pdf_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
