# Generated by Django 5.0.2 on 2024-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0018_optionalaccessoriespreise_pdf_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionalaccessoriespreise",
            name="pdf_text",
            field=models.TextField(blank=True, default="", help_text="Inhalt"),
        ),
    ]
