# Generated by Django 5.0.2 on 2024-11-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0021_rabattaktion_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RabattAktion",
            new_name="Sonderrabatt",
        ),
        migrations.RenameField(
            model_name="prices",
            old_name="rabatt_aktion",
            new_name="sonder_rabatt",
        ),
    ]
