# Generated by Django 5.0.2 on 2025-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0022_rename_rabattaktion_sonderrabatt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sonderrabatt",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
