# Generated by Django 5.0.2 on 2025-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0023_sonderrabatt_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="anderekonfigurationwerte",
            name="text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
