# Generated by Django 5.0.2 on 2025-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0024_anderekonfigurationwerte_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLZAufpreisNachkauf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
                ("text", models.TextField(blank=True, default="")),
            ],
        ),
    ]
