# Generated by Django 5.0.2 on 2025-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0025_plzaufpreisnachkauf"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrTauschPreise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pdf_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pdf_text",
                    models.TextField(blank=True, default="", help_text="Inhalt"),
                ),
            ],
        ),
    ]
