# Generated by Django 5.0.2 on 2025-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0026_wrtauschpreise"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionalaccessoriespreise",
            name="price_other",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallboxpreise",
            name="price_other",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
