# Generated by Django 4.2.5 on 2023-11-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datenblatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solar_module_1", models.BinaryField(blank=True, null=True)),
                ("solar_module_2", models.BinaryField(blank=True, null=True)),
                ("solar_module_3", models.BinaryField(blank=True, null=True)),
                ("speicher_module", models.BinaryField(blank=True, null=True)),
                ("wall_box", models.BinaryField(blank=True, null=True)),
                ("wechselrichter", models.BinaryField(blank=True, null=True)),
                ("backup_box", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
