# Generated by Django 4.2.5 on 2023-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datenblatter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datenblatter",
            name="backup_box",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="solar_module_1",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="solar_module_2",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="solar_module_3",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="speicher_module",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="wall_box",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="datenblatter",
            name="wechselrichter",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
