# Generated by Django 4.2.5 on 2024-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datenblatter", "0002_alter_datenblatter_backup_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="optimizer",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
