# Generated by Django 5.0.2 on 2024-03-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0003_datenblatter_optimizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="backup_box_viessmann",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="optimizer_viessmann",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="solar_module_4",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="speicher_module_viessmann",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="wall_box_viessman",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="wechselrichter_viessman",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
