# Generated by Django 5.0.2 on 2024-03-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0004_datenblatter_backup_box_viessmann_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="ac_thor",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="huawei_power_sensor",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="huawei_smart_energie_controller",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="viessmann_allgemeine_bedingungen",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="viessmann_tigo",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="viessmann_versicherung_ausweis",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
