# Generated by Django 5.0.2 on 2024-04-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0005_datenblatter_ac_thor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="speicher_module_huawei7",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
