# Generated by Django 5.0.2 on 2024-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0006_datenblatter_speicher_module_huawei7"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datenblatter",
            old_name="huawei_power_sensor",
            new_name="huawei_smartmeter_dtsu",
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="huawei_smartmeter_emma",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
