# Generated by Django 5.0.2 on 2024-06-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "datenblatter",
            "0007_rename_huawei_power_sensor_datenblatter_huawei_smartmeter_dtsu_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datenblatter",
            name="solar_module_1",
        ),
        migrations.RemoveField(
            model_name="datenblatter",
            name="solar_module_2",
        ),
        migrations.RemoveField(
            model_name="datenblatter",
            name="solar_module_3",
        ),
        migrations.RemoveField(
            model_name="datenblatter",
            name="solar_module_4",
        ),
    ]
