# Generated by Django 5.0.2 on 2024-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0008_remove_datenblatter_solar_module_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datenblatter",
            name="wall_box",
        ),
        migrations.RemoveField(
            model_name="datenblatter",
            name="wall_box_viessman",
        ),
    ]
