# Generated by Django 5.0.2 on 2024-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0009_remove_datenblatter_wall_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="finanzierung",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
