# Generated by Django 5.0.2 on 2024-11-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0010_datenblatter_finanzierung"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="ac_elwa",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
