# Generated by Django 5.0.2 on 2025-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0011_datenblatter_ac_elwa"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="wechselrichter_map0",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="datenblatter",
            name="wechselrichter_mb0",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
