# Generated by Django 5.0.2 on 2025-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0012_datenblatter_wechselrichter_map0_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="smartguard",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
