# Generated by Django 5.0.2 on 2025-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0013_datenblatter_smartguard"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="speicher_module_atmoce",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
