# Generated by Django 5.0.2 on 2025-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datenblatter", "0014_datenblatter_speicher_module_atmoce"),
    ]

    operations = [
        migrations.AddField(
            model_name="datenblatter",
            name="smartmeter_atmoce",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
