# Generated by Django 4.2.2 on 2023-07-09 12:53

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("zoho_id", models.PositiveBigIntegerField(null=True, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100, null=True, unique=True)),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("age", models.PositiveSmallIntegerField(default=2, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="phone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/images/users/"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "beruf",
                    models.CharField(
                        choices=[
                            ("Elektriker", "Elektriker"),
                            ("Vertrieb", "Vertrieb"),
                        ],
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                ("users_aufschlag", models.PositiveSmallIntegerField(default=0)),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("keine", "keine"),
                            ("Evolti", "Evolti"),
                            ("Vertrieb", "Vertrieb"),
                            ("Freelancer", "Freelancer"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                ("kuerzel", models.CharField(max_length=3, null=True, unique=True)),
                ("gerat", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("imei", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("anbieter", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "google_account",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "google_passwort",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("sim_pin", models.SmallIntegerField(blank=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("zoho_data", models.JSONField(blank=True, default=dict)),
                ("zoho_data_text", models.TextField(blank=True, default="")),
                ("sonstiges", models.TextField(blank=True, null=True)),
                (
                    "smtp_server",
                    models.CharField(
                        blank=True, default="send.one.com", max_length=50, null=True
                    ),
                ),
                (
                    "smtp_port",
                    models.CharField(
                        blank=True, default="587", max_length=10, null=True
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True,
                        default="si@juno-solar.com",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True, default="301c81Pq8", max_length=30, null=True
                    ),
                ),
                (
                    "smtp_subject",
                    models.TextField(
                        blank=True, default="Juno-Solar Dokument-Anlage", null=True
                    ),
                ),
                (
                    "smtp_body",
                    models.TextField(
                        blank=True,
                        default="Sehr geehrter Kunde, in diesem Schreiben finden Sie die beigefügten PDF-Dokumente.\n\n                                                                    Mit freundlichen Grüßen, Juno-Solar",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.role",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
    ]
