# Generated by Django 4.2.2 on 2023-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="beruf",
            field=models.CharField(
                choices=[
                    ("Elektriker", "Elektriker"),
                    ("Vertrieb", "Vertrieb"),
                    ("Projektant", "Projektant"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
