# Generated by Django 4.2.2 on 2023-08-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_top_verkaufer_container_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activity_container_view",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="angebot_statusubersicht_view",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="anzahl_sol_module_view",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_container_view",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pv_rechner_view",
            field=models.BooleanField(default=True),
        ),
    ]
