# Generated by Django 4.2.2 on 2023-08-28 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_activity_container_view_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_change_user", "Can change user")],
                "verbose_name_plural": "Users",
            },
        ),
    ]
