# Generated by Django 4.2.2 on 2023-09-19 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initial_anzOptimizer",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_anz_speicher",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_arbeitspreis",
            field=models.FloatField(
                default=46.8, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_ausrichtung",
            field=models.CharField(default="Ost/West", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_bis10kWp",
            field=models.FloatField(
                default=8.2, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_bis40kWp",
            field=models.FloatField(
                default=7.1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_elwa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_garantieWR",
            field=models.CharField(default="10 Jahre", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_grundpreis",
            field=models.FloatField(
                default=9.8, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_heizstab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_komplex",
            field=models.CharField(default="sehr komplex", max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_modulanzahl",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_notstrom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_prognose",
            field=models.FloatField(
                default=5.2, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_solar_module",
            field=models.CharField(
                default="Phono Solar PS420M7GFH-18/VNH", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_thor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_verbrauch",
            field=models.FloatField(
                default=15000, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_wallbox_anzahl",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_wallboxtyp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_wandhalterung_fuer_speicher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="initial_zeitraum",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="user",
            name="intial_kabelanschluss",
            field=models.FloatField(
                blank=True,
                default=10.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="map_notizen_container_view",
            field=models.CharField(
                choices=[("Map", "Map"), ("Notizen", "Notizen")], default="Map"
            ),
        ),
    ]
