# Generated by Django 4.2.5 on 2023-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_user_user_certifikate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_home_page",
            field=models.BooleanField(default=True),
        ),
    ]
