# Generated by Django 4.2.5 on 2023-11-28 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_user_initial_text_for_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="intial_kabelanschluss",
            new_name="initial_kabelanschluss",
        ),
    ]
