# Generated by Django 5.0.2 on 2024-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0012_rename_intial_kabelanschluss_user_initial_kabelanschluss",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="map_notizen_container_view",
            field=models.CharField(
                choices=[("Map", "Map"), ("Notizen", "Notizen")],
                default="Map",
                max_length=2000,
            ),
        ),
    ]
