# Generated by Django 5.0.2 on 2024-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_user_map_notizen_container_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="records_fetch_limit",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
