# Generated by Django 5.0.2 on 2024-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_user_records_fetch_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="smtp_password",
            field=models.CharField(
                blank=True, default="e4e4e3Qm8", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="smtp_username",
            field=models.CharField(
                blank=True, default="info@juno-solar.com", max_length=30, null=True
            ),
        ),
    ]
