# Generated by Django 5.0.2 on 2024-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_user_smtp_password_alter_user_smtp_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="anbieter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gerat",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_account",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_passwort",
        ),
        migrations.RemoveField(
            model_name="user",
            name="imei",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sim_pin",
        ),
    ]
