# Generated by Django 5.0.2 on 2024-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_user_age_remove_user_anbieter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="beruf",
            field=models.CharField(
                choices=[
                    ("Vertrieb", "Vertrieb"),
                    ("Projektant", "Projektant"),
                    ("Elektriker", "Elektriker"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
