# Generated by Django 5.0.2 on 2024-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_alter_user_beruf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="records_fetch_limit",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
