# Generated by Django 5.0.2 on 2024-08-08 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_user_records_fetch_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initial_bis10kWp",
            field=models.FloatField(
                default=8.03, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="initial_bis40kWp",
            field=models.FloatField(
                default=6.95, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
