# Generated by Django 5.0.2 on 2024-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_alter_user_initial_bis10kwp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initial_garantieWR",
            field=models.CharField(default="15 Jahre", max_length=10),
        ),
    ]
