# Generated by Django 5.0.2 on 2024-08-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_alter_user_initial_garantiewr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initial_garantieWR",
            field=models.CharField(default="10 Jahre", max_length=10),
        ),
    ]
