# Generated by Django 5.0.2 on 2025-02-04 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initial_bis10kWp",
            field=models.FloatField(
                default=7.95, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="initial_bis40kWp",
            field=models.FloatField(
                default=6.88, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
