# Generated by Django 5.0.2 on 2025-02-14 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_alter_user_initial_bis10kwp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initial_kabelanschluss",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
