# Generated by Django 5.0.2 on 2025-02-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_alter_user_initial_kabelanschluss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="smtp_body",
            field=models.TextField(
                blank=True,
                default="Mit freundlichen Grüßen / Kind regards\nName\nStellenbezeichnung \n\nT: +49 3761 4170800\nM: \nE: @juno-solar.com \nI: www.juno-solar.com\n\nJuno Solar Home GmbH & Co. KG\nZiegelstraße 1a\nD-08412 Werdau\n            \nJuno Solar Home GmbH & Co. KG \nGeschäftsführer: Denny Schädlich\nRegistergericht: Amtsgericht Chemnitz, HRA 9415 \nVertreten durch Juno Solar Home Verwaltungs GmbH \n\nDiese Nachricht ist vertraulich. Sie darf ausschließlich durch den vorgesehenen Empfänger und Adressat gelesen, kopiert oder genutzt werden. Sollten Sie diese Nachricht versehentlich erhalten haben, bitten wir, den Absender (durch Antwort-E-Mail) hiervon unverzüglich zu informieren und die Nachricht zu löschen. Jede Nutzung oder Weitergabe des Inhalts dieser Nachricht ist unzulässig. \n\nThis message (including any attachments) is confidential and may be privileged. It may be read, copied and used only by the intended recipient. If you have received it in error, please contact the sender (by return e-mail) immediately and delete this message. Any unauthorised use or dissemination of this message in whole or in part is strictly prohibited.\n",
                null=True,
            ),
        ),
    ]
