# Generated by Django 5.0.2 on 2025-03-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_alter_user_smtp_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="records_fetch_limit",
            field=models.PositiveIntegerField(default=400),
        ),
    ]
