# Generated by Django 5.0.2 on 2025-03-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_user_records_fetch_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="typ",
            field=models.CharField(
                choices=[
                    ("keine", "keine"),
                    ("Handelsvertretung", "Handelsvertretung"),
                    ("Vertrieb", "Vertrieb"),
                    ("Regionalleitung", "Regionalleitung"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
