# Generated by Django 5.0.2 on 2025-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_alter_user_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salutation",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="typ",
            field=models.CharField(
                choices=[
                    ("Handelsvertretung", "Handelsvertretung"),
                    ("Vertrieb", "Vertrieb"),
                    ("Regionalleitung", "Regionalleitung"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
