# Generated by Django 5.0.2 on 2025-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_alter_user_smtp_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="typ",
            field=models.CharField(
                choices=[
                    ("Handelsvertretung", "Handelsvertretung"),
                    ("Vertrieb", "Vertrieb"),
                    ("Regionalleitung", "Regionalleitung"),
                    ("Kooperationspartner", "Kooperationspartner"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
