# Generated by Django 5.0.2 on 2025-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_user_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="salutation",
            field=models.CharField(
                choices=[("Herr", "Herr"), ("Frau", "Frau"), ("Firma", "Firma")],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
