# Generated by Django 5.0.2 on 2025-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_alter_user_salutation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="smtp_port",
            field=models.CharField(
                blank=True, default="2525", max_length=10, null=True
            ),
        ),
    ]
