# Generated by Django 5.0.2 on 2025-10-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_alter_user_smtp_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="initial_notstrom",
        ),
    ]
