# Generated by Django 4.2.2 on 2023-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculator",
            name="elwa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calculator",
            name="elwa_typ",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="calculator",
            name="heizstab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calculator",
            name="thor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calculator",
            name="thor_typ",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
