# Generated by Django 5.0.2 on 2024-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_calculator_elwa_calculator_elwa_typ_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculator",
            name="garantieWR",
            field=models.CharField(
                choices=[("keine", "keine"), ("15 Jahre", "15 Jahre")],
                default="keine",
                max_length=10,
            ),
        ),
    ]
