# Generated by Django 5.0.2 on 2024-07-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_alter_calculator_garantiewr"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculator",
            name="speicher_model",
            field=models.CharField(default="LUNA 2000-7-S1", max_length=100),
        ),
    ]
