# Generated by Django 5.0.2 on 2024-08-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_calculator_speicher_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculator",
            name="elwa_typ",
        ),
        migrations.RemoveField(
            model_name="calculator",
            name="thor_typ",
        ),
    ]
