# Generated by Django 5.0.2 on 2025-10-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_remove_calculator_eddi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculator",
            name="notstrom",
        ),
        migrations.RemoveField(
            model_name="calculator",
            name="notstrom_angebot_price",
        ),
    ]
