# Generated by Django 4.2.2 on 2023-07-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elektriker_kalender.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricCalendar",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar_id",
                    models.CharField(
                        default=None,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("zoho_id", models.CharField(default="", max_length=20)),
                ("current_date", models.DateField(auto_now_add=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "anschluss_PVA",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("elektriker_calfield", models.BigIntegerField(blank=True, null=True)),
                ("kundenname", models.CharField(blank=True, max_length=255, null=True)),
                ("pva_klein1_calfield", models.BigIntegerField(blank=True, null=True)),
                (
                    "privatkunde_adresse_pva",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "besonderheiten",
                    models.TextField(blank=True, default="Besonderheiten", null=True),
                ),
                ("elektriktermin_am", models.DateTimeField(blank=True, null=True)),
                (
                    "kundenname_rawdata",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "termin_best_tigt",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PVAKlein1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("pva_id", models.CharField(max_length=20)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pva_kleins1",
                        to="elektriker_kalender.electriccalendar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Hauptleitungsabzweigklemmen 35mm",
                                "Hauptleitungsabzweigklemmen 35mm",
                            ),
                            ("Kabelschellen Metall", "Kabelschellen Metall"),
                            ("Kabelkanal 10x60mm", "Kabelkanal 10x60mm"),
                            ("Kabelkanal 30x30mm", "Kabelkanal 30x30mm"),
                            ("Kabelkanal 60x60mm", "Kabelkanal 60x60mm"),
                            (
                                "Mantellleitung NYY-J 5x16qmm",
                                "Mantellleitung NYY-J 5x16qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x16qmm",
                                "Mantellleitung NYM-J 5x16qmm",
                            ),
                            (
                                "Mantellleitung NYY-J 1x16qmm",
                                "Mantellleitung NYY-J 1x16qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 1x16qmm",
                                "Mantellleitung NYM-J 1x16qmm",
                            ),
                            (
                                "Mantellleitung NYY-J 5x10qmm",
                                "Mantellleitung NYY-J 5x10qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x10qmm",
                                "Mantellleitung NYM-J 5x10qmm",
                            ),
                            (
                                "Mantellleitung NYY-J 5x6qmm",
                                "Mantellleitung NYY-J 5x6qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x6qmm",
                                "Mantellleitung NYM-J 5x6qmm",
                            ),
                            (
                                "Mantellleitung NYY-J 5x4qmm",
                                "Mantellleitung NYY-J 5x4qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x4qmm",
                                "Mantellleitung NYM-J 5x4qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x2.5qmm",
                                "Mantellleitung NYM-J 5x2.5qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 3x2.5qmm",
                                "Mantellleitung NYM-J 3x2.5qmm",
                            ),
                            (
                                "Mantellleitung NYM-J 5x1.5qmm",
                                "Mantellleitung NYM-J 5x1.5qmm",
                            ),
                            ("H07-VK 16mm² sw", "H07-VK 16mm² sw"),
                            ("H07-VK 16mm² bl", "H07-VK 16mm² bl"),
                            ("H07-VK 16mm² gn/ge", "H07-VK 16mm² gn/ge"),
                            ("H07-VK 10mm² sw", "H07-VK 10mm² sw"),
                            ("H07-VK 10mm² bl", "H07-VK 10mm² bl"),
                            ("H07-VK 10mm² gn/ge", "H07-VK 10mm² gn/ge"),
                            ("H07-VK 4mm² sw", "H07-VK 4mm² sw"),
                            ("H07-VK 4mm² bl", "H07-VK 4mm² bl"),
                            ("H07-VK 4mm² gn/ge", "H07-VK 4mm² gn/ge"),
                            ("H07-VK 2.5mm² sw", "H07-VK 2.5mm² sw"),
                            ("H07-VK 2.5mm² bl", "H07-VK 2.5mm² bl"),
                            ("H07-VK 2.5mm² gn/ge", "H07-VK 2.5mm² gn/ge"),
                            (
                                "Leitungsschutzschalter 3polig B16 leGrand",
                                "Leitungsschutzschalter 3polig B16 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 3polig B20 leGrand",
                                "Leitungsschutzschalter 3polig B20 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 3polig B25 leGrand",
                                "Leitungsschutzschalter 3polig B25 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 3polig B32 leGrand",
                                "Leitungsschutzschalter 3polig B32 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 3polig B40 leGrand",
                                "Leitungsschutzschalter 3polig B40 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 1polig B10 leGrand",
                                "Leitungsschutzschalter 1polig B10 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 1polig B16 leGrand",
                                "Leitungsschutzschalter 1polig B16 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 1polig B20 leGrand",
                                "Leitungsschutzschalter 1polig B20 leGrand",
                            ),
                            (
                                "Leitungsschutzschalter 1polig B25 leGrand",
                                "Leitungsschutzschalter 1polig B25 leGrand",
                            ),
                            ("SLS  3polig E35A", "SLS  3polig E35A"),
                            ("SLS  3polig E50A", "SLS  3polig E50A"),
                            ("SLS  3polig E63A", "SLS  3polig E63A"),
                            (
                                "Uberspannungsschutz (Kombiableiter Phasenschiene DEHN)",
                                "Uberspannungsschutz (Kombiableiter Phasenschiene DEHN)",
                            ),
                            (
                                "Uberspannungsschutz (Kombiableiter Hutschiene DEHN)",
                                "Uberspannungsschutz (Kombiableiter Hutschiene DEHN)",
                            ),
                            ("Hauptschalter 3x63A", "Hauptschalter 3x63A"),
                            (
                                "Fehlerstromschutzschalter 4polig 40A/30mA",
                                "Fehlerstromschutzschalter 4polig 40A/30mA",
                            ),
                            ("FI/LS 2polig 16A/30mA", "FI/LS 2polig 16A/30mA"),
                            ("FI/LS 2polig 25A/30mA", "FI/LS 2polig 25A/30mA"),
                            ("FI/LS 4polig 16A/30mA", "FI/LS 4polig 16A/30mA"),
                            ("FI/LS 4polig 25A/30mA", "FI/LS 4polig 25A/30mA"),
                            ("Kammschiene 3phasig HAGER", "Kammschiene 3phasig HAGER"),
                            (
                                "Kammschiene 3phasig HAGER (N)",
                                "Kammschiene 3phasig HAGER (N)",
                            ),
                            (
                                "Phoenixkontakt-Klemmen PE/L/NT",
                                "Phoenixkontakt-Klemmen PE/L/NT",
                            ),
                            (
                                "Phoenixkontakt-Klemmen L/L",
                                "Phoenixkontakt-Klemmen L/L",
                            ),
                            (
                                "Phoenixkontakt-Einspeiseklemme N",
                                "Phoenixkontakt-Einspeiseklemme N",
                            ),
                            ("Kupferschiene N", "Kupferschiene N"),
                            (
                                "Phoenixkontakt-Einspeiseklemme N Seitendeckel",
                                "Phoenixkontakt-Einspeiseklemme N Seitendeckel",
                            ),
                            (
                                "Phoenixkontakt-Stufenklemmen",
                                "Phoenixkontakt-Stufenklemmen",
                            ),
                            (
                                "Phoenixkontakt-Klemmen Seitendeckel grau",
                                "Phoenixkontakt-Klemmen Seitendeckel grau",
                            ),
                            ("Endkappen Kammschiene", "Endkappen Kammschiene"),
                            (
                                "Berührungsschutz Kammschiene",
                                "Berührungsschutz Kammschiene",
                            ),
                            ("Klemmblock Hutschiene N", "Klemmblock Hutschiene N"),
                            ("Klemmblock Hutschiene PE", "Klemmblock Hutschiene PE"),
                            ("WAGO-Klemmen (-4mm²)", "WAGO-Klemmen (-4mm²)"),
                            ("WAGO-Klemmen (-6mm²)", "WAGO-Klemmen (-6mm²)"),
                            ("WAGO-Klemmen (-10mm²)", "WAGO-Klemmen (-10mm²)"),
                            (
                                "Hutschienenhalter WAGO-Klemmen",
                                "Hutschienenhalter WAGO-Klemmen",
                            ),
                            ("Aufputz-Abzweigdosen", "Aufputz-Abzweigdosen"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("quantity", models.FloatField(blank=True, null=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        default=elektriker_kalender.models.ElectricCalendar,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="elektriker_kalender.electriccalendar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
