# Generated by Django 4.2.2 on 2023-08-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bautermine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Elektriktermin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Module1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Speicher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallbox1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wechselrichter1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_value", models.CharField(max_length=255)),
                ("ID", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "ID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("Status", models.CharField(max_length=255)),
                ("Auftragsbest_tigung_versendet", models.CharField(max_length=5)),
                ("Auftrag_Erteilt_am", models.DateField(blank=True, null=True)),
                ("Kunde_display_value", models.CharField(max_length=255)),
                ("Kunde_ID", models.CharField(max_length=50)),
                ("Modul_Summe_kWp", models.CharField(blank=True, max_length=255)),
                ("Besonderheiten", models.TextField()),
                ("Rechnung_versandt", models.CharField(blank=True, max_length=255)),
                ("Lieferung", models.DateField(blank=True, null=True)),
                (
                    "Berechnung_erhalten_am",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("EDDI", models.BooleanField(default=False)),
                (
                    "Netzbetreiber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Garantie_WR_beantragt_am",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Ticket_form",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Status_Inbetriebnahmeprotokoll",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Zahlungsmodalit_ten",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Berechnung_bergeben_am",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Vertriebler",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Notstromversorgung_Backup_Box_vorhanden",
                    models.BooleanField(default=False),
                ),
                (
                    "Status_Marktstammdatenregistrierung",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Garantieerweiterung",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Bauabschluss_am",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Status_Betreiberwechsel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Status_Einspeiseanfrage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Hub1", models.BooleanField(default=False)),
                (
                    "Kunde_Kundennummer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("UK_auf_Lager", models.BooleanField(default=False)),
                (
                    "UK_bestellt_am",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Power_Boost_vorhanden", models.BooleanField(default=False)),
                (
                    "Unterkonstruktion1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Harvi1", models.CharField(blank=True, max_length=255, null=True)),
                ("Optimizer1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Kunde_Adresse_PVA",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Status_Elektrik",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Kunde_Email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Termin_Z_hlerwechsel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Nummer_der_PVA",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Kunde_Postanschrift",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Kunde_Telefon_Festnetz",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Status_Fertigmeldung",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Bauleiter", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Hauselektrik",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Kunde_Telefon_mobil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Bautermine",
                    models.ManyToManyField(to="projektant_interface.bautermine"),
                ),
                (
                    "Elektriktermin",
                    models.ManyToManyField(to="projektant_interface.elektriktermin"),
                ),
                ("Module1", models.ManyToManyField(to="projektant_interface.module1")),
                (
                    "Speicher",
                    models.ManyToManyField(to="projektant_interface.speicher"),
                ),
                (
                    "Wallbox1",
                    models.ManyToManyField(to="projektant_interface.wallbox1"),
                ),
                (
                    "Wechselrichter1",
                    models.ManyToManyField(to="projektant_interface.wechselrichter1"),
                ),
            ],
        ),
    ]
