# Generated by Django 4.2.2 on 2023-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="Bautermine",
        ),
        migrations.RemoveField(
            model_name="project",
            name="Elektriktermin",
        ),
        migrations.RemoveField(
            model_name="project",
            name="Module1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="Speicher",
        ),
        migrations.RemoveField(
            model_name="project",
            name="Wallbox1",
        ),
        migrations.RemoveField(
            model_name="project",
            name="Wechselrichter1",
        ),
        migrations.AddField(
            model_name="project",
            name="Bautermine",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="Elektriktermin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="Module1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="Speicher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="Wallbox1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="Wechselrichter1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
