# Generated by Django 4.2.2 on 2023-08-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0002_remove_project_bautermine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Processed_Besonderheiten",
            field=models.TextField(default="keine Beschreibung"),
        ),
    ]
