# Generated by Django 4.2.2 on 2023-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0003_project_processed_besonderheiten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="Wechselrichter1",
            field=models.TextField(blank=True, null=True),
        ),
    ]
