# Generated by Django 4.2.2 on 2023-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0006_project_kunden_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="solar_module",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
