# Generated by Django 4.2.2 on 2023-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0007_project_solar_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
