# Generated by Django 4.2.2 on 2023-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0008_project_ticket_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vertriebler",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
