# Generated by Django 4.2.2 on 2023-08-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0009_project_vertriebler"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="speicher",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="unterkonstrution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wallbox",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="wechselrichter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
