# Generated by Django 4.2.2 on 2023-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projektant_interface",
            "0010_project_speicher_project_unterkonstrution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="height",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="roof_typ",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
