# Generated by Django 4.2.2 on 2023-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0011_project_height_project_roof_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="current_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
