# Generated by Django 4.2.2 on 2023-09-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0013_project_temp_content_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="bauplan_img",
            field=models.ImageField(blank=True, null=True, upload_to="assets/images/"),
        ),
    ]
