# Generated by Django 4.2.2 on 2023-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0014_alter_project_bauplan_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bauplan_img_secondary",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/images/layouts/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="bauplan_img_third",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/images/layouts/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="bauplan_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/images/layouts/"
            ),
        ),
    ]
