# Generated by Django 4.2.2 on 2023-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projektant_interface", "0015_project_bauplan_img_secondary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="email_form",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="font_size",
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
    ]
